#!/bin/bash
############################################################################################
#zoom_level
############################################################################################
zoom_desc[1]=INTER-REGION
zoom_level[1]=1
zoom_GM[1]=7
zoom_region[1]=150000
zoom_dx[1]=500

zoom_desc[2]=REGION
zoom_level[2]=2
zoom_GM[2]=8
zoom_region[2]=75000
zoom_dx[2]=250

zoom_desc[3]=REGION
zoom_level[3]=3
zoom_GM[3]=9
zoom_region[3]=45000
zoom_dx[3]=150

zoom_desc[4]=DEPARTEMENT
zoom_level[4]=4
zoom_GM[4]=10
zoom_region[4]=30000
zoom_dx[4]=75

zoom_desc[5]=AGGLO
zoom_level[5]=5
zoom_GM[5]=11
zoom_region[5]=15000
zoom_dx[5]=50

zoom_desc[6]=VILLE
zoom_level[6]=6
zoom_GM[6]=12
zoom_region[6]=9000
zoom_dx[6]=25

zoom_desc[7]=VILLAGE
zoom_level[7]=7
zoom_GM[7]=13
zoom_region[7]=3000
zoom_dx[7]=10

zoom_desc[8]=QUARTIER
zoom_level[8]=8
zoom_GM[8]=14
zoom_region[8]=2000
zoom_dx[8]=5  

#Zoom pour la suremission (OBSOLETE)
zoom_desc[9]=PREVALP
zoom_level[9]=9
zoom_GM[9]=9
zoom_region[9]=9000
zoom_dx[9]=3000 
